### ISSUE TITLE
Don't download this

### ISSUE THREAD

**Issue by Mikaka27** [CJxD/avr-eeprom-fs#1]
This doesn't compile, requires a lot of fixes before it does. Then there are errors with length calculation upon appending. File length is added upon appending and then added again after closing file.

**Comment by CJxD** [comment]
You could always submit revisions! I knew there were errors with appending but I was only allowed a week of development time.

**Comment by Mikaka27** [comment]
I'll sure do that, when it will pass the tests. Please add some readme about the errors if you're aware of them next time. Thank you.

**Comment by CJxD** [comment]
Added this information to the README
